POST https://cautious-palm-tree-555p6qq5p5x375v9-8000.app.github.dev/atrain
###
GET https://cautious-palm-tree-555p6qq5p5x375v9-8000.app.github.dev/and/left/0/right/0
###
POST https://cautious-palm-tree-555p6qq5p5x375v9-8000.app.github.dev/otrain
###
GET https://cautious-palm-tree-555p6qq5p5x375v9-8000.app.github.dev/or/left/1/right/0
###
POST https://cautious-palm-tree-555p6qq5p5x375v9-8000.app.github.dev/ntrain
###
GET https://cautious-palm-tree-555p6qq5p5x375v9-8000.app.github.dev/not/input/1
###
POST https://cautious-palm-tree-555p6qq5p5x375v9-8000.app.github.dev/xtrain
###
GET https://cautious-palm-tree-555p6qq5p5x375v9-8000.app.github.dev/xor/left/0/right/1
###
